# Copyright 2025 PopaiTheSailor Authors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: CD

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install tools
        run: sudo apt-get install --yes leiningen

      - name: Restore build cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57
        with:
          restore-keys: clojure-
          key:          clojure-${{ hashFiles('**/project.clj') }}
          path: |
            ~/.m2/repository/
            target/

      - name: Build uberjar
        run: lein uberjar

      - name: Deploy server
        run: |
          TOKEN=$(curl \
            --header "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            --url    "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=prod-deploy" \
            | jq --raw-output .value)

          curl \
            --fail-with-body \
            --silent \
            --data-binary @target/com.popaithesailor.www-unversioned-standalone.jar \
            --header      "Authorization: Bearer $TOKEN" \
            --url         https://www.popaithesailor.com/i/deploy
